site_name: Formal Methods
site_url: https://formalmethods.io

theme: 
  name: material
  favicon: img/formal_methods_favicon.svg
  features:
    - content.tooltips
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: red

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  font:
    text: Merriweather Sans
    code: Source Code Pro

  logo: img/formal_methods_icon.svg

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


  - pymdownx.tabbed:
      alternate_style: true  
  - pymdownx.snippets
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
        - includes/external-links.md
  - toc:
      permalink: "#"


  - pymdownx.arithmatex:
      generic: true


watch:
  - includes
nav:
  - Home: index.md

  - FM Crypto:
    - OTP:
      - Basics: crypto/otp/basics.md
      - Perfect Secrecy: crypto/otp/perfect-secrecy.md
      - OTP in Lean: crypto/otp/otp-lean.md
      - Presentation Notes:
          - 2025 Jun 19: crypto/otp/2025Jun19-notes.md
          - 2025 Jun 18: crypto/otp/2025Jun18-notes.md
          - Old Overview/Demo: crypto/otp/interleaved_demo_presentation.md
          - Older presentation: crypto/otp/slides.md
        # reveal_slides.html
    - Mathlib:
      - Vector and List: crypto/Mathlib/vector-and-list.md
      - Probability: crypto/Mathlib/prob.md
      - Deep Dive:
          - Distributions in Lean: crypto/Mathlib/DistributionsInLean.md
          - Why [0, ∞] for Distributions?: crypto/Mathlib/WhyExtendedNNReals.md
          - Joint Distributions with bind: crypto/Mathlib/bind_and_pure.md

  - Miscellany:
    - MkDocs doc:
      - MkDocs: mkdocs.md
      - Admonitions: mkdocs/admonitions.md
      - Diagrams: mkdocs/diagrams.md
      - Code blocks: mkdocs/code-blocks.md
      - Content tabs: mkdocs/content-tabs.md

  - About:
    - Contributors: contributors.md
    - License: license.md

plugins:
  - search


extra:
  social:
    - icon: simple/github
      link: https://github.com/formalverification/formalmethods.io

extra_javascript:
  # - javascripts/katex.js
  # - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
# extra_css:
#   - https://unpkg.com/katex@0/dist/katex.min.cssextra_javascript:
#   - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
